/* empty css                      */import{i as g}from"./assets/vendor-DVYrn7a6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();class d{constructor(t,r,i){this.name=t,this.filter=r,this.imgUrl=i}static fromJson(t){return new d(t.name,t.filter,t.imgURL)}}class m{constructor(t,r,i,e){this.page=t,this.perPage=r,this.totalPages=i,this.results=e}static fromJson(t){const r=t.results.map(i=>d.fromJson(i));return new m(t.page,t.perPage,t.totalPages,r)}}const p=class p{};p.ApiBaseUrl="https://your-energy.b.goit.study/api";let u=p;async function h(n){const t=`${u.ApiBaseUrl}/filters?filter=${encodeURIComponent(n.filter)}&page=${n.page}&limit=${n.limit}`,r=await fetch(t);if(!r.ok)throw new Error(`Failed to fetch filters: ${r.status}`);const i=await r.json();return m.fromJson(i)}function w(n){return n.map(t=>`
          <div class="filter-card">
            <img src="${t.imgUrl}" alt="${t.name}" />
            <div class="filter-info">
              <div class="filter-name">${t.name}</div>
              <div class="filter-type">${t.filter}</div>
            </div>
          </div>
        `).join("")}function y(n,t){const r=[];return r.push(1),n>=2&&r.push(2),n>=3&&r.push(3),r.map(i=>`
    <span class="pagination-page${i===t?" active":""}" data-page="${i}">${i}</span>
  `).join("")}const v=({title:n,message:t,position:r,...i}={title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})=>{g.error({title:n,message:t,position:r,...i})};function L(){var c;const n=document.querySelector(".filters-output"),t=document.querySelector(".filter-tabs"),r=document.querySelector(".filter-pagination");if(!n)throw new Error("Can't find .filters-output");if(!t)throw new Error("Can't find .filter-tabs");if(!r)throw new Error("Can't find .filter-pagination");let i=(c=t.querySelector(".active"))==null?void 0:c.dataset.filter,e=1;function s(f,o){h({filter:f,page:o,limit:12}).then(l=>{n.innerHTML=w(l.results),r.innerHTML=y(l.totalPages,o)}).catch(l=>v({title:"Error",message:l.message,position:"topRight",timeout:5e3}))}t.addEventListener("click",f=>{const o=f.target;if(o.tagName.toLowerCase()!=="li")return;const a=o.dataset.filter;!a||a===i||(t.querySelectorAll("li").forEach(l=>l.classList.remove("active")),o.classList.add("active"),i=a,e=1,s(i,e))}),r.addEventListener("click",f=>{const o=f.target;if(o.tagName.toLowerCase()!=="span")return;const a=Number(o.dataset.page);!a||a===e||(e=a,s(i,e))}),s(i,e)}L();
//# sourceMappingURL=index.js.map
