/* empty css                      */import{i as p,a as h}from"./assets/vendor-BAoYjrW1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const y="https://your-energy.b.goit.study/api/",f=({title:t,message:e,position:o,...i}={title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})=>{p.error({title:t,message:e,position:o,...i})},b=({title:t,message:e,position:o,...i}={title:"Success",message:"Operation completed successfully.",position:"topRight"})=>{p.success({title:t,message:e,position:o,...i})},w=async(t,e)=>{try{const{data:o}=await h.get(`${y}${t}`,{params:e});return o}catch(o){console.error(o),f()}},v=async(t,e)=>{try{const{data:o}=await h.post(`${y}${t}`,e);return o}catch(o){console.error(o),f()}};async function C(t){const e=await w("filters",t);if(!e)throw new Error("Cant' get filters");return e}function L(t){return t.map(e=>`
          <div class="filter-card">
            <img src="${e.imgURL}" alt="${e.name}" />
            <div class="filter-info">
              <div class="filter-name">${e.name}</div>
              <div class="filter-type">${e.filter}</div>
            </div>
          </div>
        `).join("")}function O(t,e){const o=[];let r=Math.max(1,e-1),n=Math.min(t,r+3-1);n-r+1<3&&(r=Math.max(1,n-3+1));for(let a=r;a<=n;a++)o.push(a);return o.map(a=>`
    <span class="pagination-page${a===e?" active":""}" data-page="${a}">${a}</span>
  `).join("")}function P(){var a;const t=document.querySelector(".filters-output"),e=document.querySelector(".filter-tabs"),o=document.querySelector(".filter-pagination");if(!t)throw new Error("Can't find .filters-output");if(!e)throw new Error("Can't find .filter-tabs");if(!o)throw new Error("Can't find .filter-pagination");let i=(a=e.querySelector(".active"))==null?void 0:a.dataset.filter,r=1;function n(u,s){C({filter:u,page:s,limit:12}).then(l=>{t.innerHTML=L(l.results),o.innerHTML=O(l.totalPages,s)}).catch(l=>f({title:"Error",message:l.message,position:"topRight"}))}e.addEventListener("click",u=>{const s=u.target;if(s.tagName.toLowerCase()!=="li")return;const c=s.dataset.filter;!c||c===i||(e.querySelectorAll("li").forEach(l=>l.classList.remove("active")),s.classList.add("active"),i=c,r=1,n(i,r))}),o.addEventListener("click",u=>{const s=u.target;if(s.tagName.toLowerCase()!=="span")return;const c=Number(s.dataset.page);!c||c===r||(r=c,n(i,r))}),n(i,r)}async function D(){const t=await w("quote");if(!t)throw new Error("Cant' get quote");return t}const m=document.getElementById("quote-text"),g=document.getElementById("quote-author"),E="quote",q="quoteDate";function S(){return new Date().toISOString().split("T")[0]}function R(){const t=localStorage.getItem(E),e=localStorage.getItem(q),o=S();if(t&&e===o)try{return JSON.parse(t)}catch(i){return console.error("Error parsing stored quote:",i),null}return null}function d(t,e){if(!m||!g)throw new Error("Can't find quote elements");m.textContent=t,g.textContent=e}function $(t,e){const o=JSON.stringify({quote:t,author:e}),i=S();localStorage.setItem(E,o),localStorage.setItem(q,i)}async function x(){try{const t=await D();return t&&t.quote?{quote:t.quote,author:t.author}:null}catch(t){return console.error("Error fetching quote:",t),null}}async function F(){if(!m||!g)throw new Error("Can't find quote elements");const t=R();if(t){d(t.quote,t.author);return}const e=await x();e?($(e.quote,e.author),d(e.quote,e.author)):d("Failed to fetch quote.","")}function T(){const t=document.getElementById("subscription-form"),e=document.querySelector(".footer-year p");if(e&&(e.textContent=`©${new Date().getFullYear()}`),!t)return;t.addEventListener("submit",o);async function o(r){r.preventDefault();const a=new FormData(t).get("email");if(!a||!i(a)){f({title:"Error",message:"Please enter a valid email address",position:"topRight"});return}try{if(await v("subscription",{email:a})===void 0)throw new Error("Subscription failed");t.reset(),b({title:"Success",message:"Thank you for subscribing!",position:"topRight"})}catch{f({title:"Error",message:"Failed to subscribe. Please try again later.",position:"topRight"})}}function i(r){return/^\w+(\.\w+)*@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(r)}}P();F();T();
//# sourceMappingURL=index.js.map
